app: web-type-scf
stage: dev
component: scf
name: web-type-scf-instance-Nodejs10.15
inputs:
  name: ${name}
  region: ap-shanghai
  runtime: Nodejs10.15
  src:
    src: ../../../
    exclude:
      - .env
      - package-lock.json
      - package.json
      - Dockerfile
      - deploy/**
      - Dockerfile*
      - workspace.code-workspace
  type: web
  handler: scf_bootstrap
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
              function:
                type: web
